### ISSUE TITLE
juno version returns "Cannot fetch last release of mission control"

### ISSUE THREAD

**Issue by ByronBecker** [junobuild/cli#127]
Hey David 👋 

Great job with Juno, just getting spun up on everything and the tooling and DX is really impressive so far!

I was playing around with the Juno CLI this morning and ran into this error. It's non blocking, but figured you might be interested.

```
% npx juno version                   
(node:58497) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Your CLI (v0.0.69) is up-to-date.
Cannot fetch last release version of mission control on Juno's CDN 😢. <--- this shows up in red error text
No config file found.
```

**Comment by peterpeterparker** [comment]
Hi Byron 👋

Cool to hear you played around with Juno!!!

I cannot reproduce the error. I ran the command at the root of one of my Juno project and in some random folder.

> Your CLI (v0.0.69) is up-to-date.
> Your mission control (v0.0.11) is up-to-date.
> No config file found.
> Your orbiter "3iier-sqaaa-aaaal-aczaa-cai" (v0.0.7) is up-to-date.

However, given that you are facing following warning:

> (node:58497) ExperimentalWarning: The Fetch API is an experimental...

It might be due to the fact that you are running the command with an older version of NodeJS.

What version of NodeJS are you using?

I'm using LTS v20.

**Comment by ByronBecker** [comment]
Hmm - this may have either been due to originally installing Juno as a local package (not with the `-g` flag), or potentially due to not having my mission control updated.

Regardless, after a global install I'm unable to reproduce this issue (Node version not a problem). Closing now.

**Comment by peterpeterparker** [comment]
Weird, let me know if it happens again please!

Nevertheless your issue was useful, the CLI was still checking for Node 18 instead of 20. I just improved that in #128.
