### ISSUE TITLE
juno deploy pre-build

### ISSUE THREAD

**Issue by peterpeterparker** [junobuild/cli#142]
We can add an option to the CLI to run `npm run build` (or yarn or pnpm) before `juno deploy`.

However, given that I think that other JS cli (Firebase etc.) does not do so, this should be an opt-in feature.

e.g. `juno deploy` -> `do you want to build it ` -> `y/n` -> `want to remember this option` -> `y/n`

**Comment by divin3circle** [comment]
Yeah, I think that would help. Or maybe throw an error when `juno deploy` doesn't find a build folder.

**Comment by peterpeterparker** [comment]
After giving it some thought, long story short, the idea would be to be more generic and future proof by supporting various predeploy scripts at the project level.

e.g.

```
import { defineConfig } from "@junobuild/config";

export default defineConfig({
  satellite: {
    id: "qsgjb-riaaa-aaaaa-aaaga-cai",
    source: "dist",
    predeploy: [
      "./run-this-script.sh",
      "npm run do-something",
      "npm run build"
    ]
  }
});
```
